[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "prynai-chainlit-ui"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
  "chainlit>=2.0.0",
  "httpx>=0.25.0"
]

[tool.hatch.build.targets.wheel]
packages = ["src"]