[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "prynai-shared"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = ["httpx>=0.25.0", "structlog>=24.1.0"]

[tool.hatch.build.targets.wheel]
packages = ["src/prynai_shared"]