name: chainlit-build-deploy
on:
  push:
    branches: [ main ]
    paths: [ "apps/chainlit-ui/**", ".github/workflows/build_deploy_chainlit.yml" ]
jobs:
  build-deploy:
    permissions: { id-token: write, contents: read }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: ${{ vars.AZ_RG }}
          containerAppName: ${{ vars.CHAINLIT_APP_NAME }}
          acrName: ${{ vars.ACR_NAME }}
          imageToBuild: ${{ vars.ACR_NAME }}.azurecr.io/prynai/chainlit:${{ github.sha }}
          dockerfilePath: apps/chainlit-ui/Dockerfile
          targetPort: 8000
          ingress: external